spring:
  data:
    mongodb:
      username: Websocket
      password: Websocket
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin

server:
  port: 8088